[mgr]
prepend_keymap = [
#{on = "<Right>", run = "plugin smart-enter"},
#{on = "<Enter>", run = "ignore"}

#Mapping
{on =["g","b"] , run = "arrow bot", desc="Go to bottom"},
# Demapping 
{on = "~", run="ignore"},
{on = "<Down>", run = "ignore"},
{on = "<Up>", run = "ignore"},
{on = "<Right>", run = "ignore"},
{on = "<Left>", run = "ignore"}
]
