
require("binds")
hl.monitor({ output = "VGA-1", mode = "1920x1080", position = "auto", scale = "1.6"})
hl.monitor({ output = "LVDS-1", mode = "1366x768", position = "auto", scale = "auto"})

-- Colors
local active_gradient_start = "rgba(00dd00ff)"
local active_gradient_end = "rgba(00dd00ff)"
local inactive_gradient_start = "rgba(666666ff)"
local inactive_gradient_end = "rgba(666666ff)"


hl.on("hyprland.start", function ()
	hl.exec_cmd("waybar")
end)

hl.env("HYPRCURSOR_SIZE",40)


hl.config({
	autogenerated = false,
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 2,

		col = {
			active_border = { colors = { active_gradient_start, active_gradient_end }},
			inactive_border = { colors = { inactive_gradient_start, inactive_gradient_end}},
		},

		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {

		dim_inactive = true,
		dim_strength = 0.75,

		blur =  {
			size = 2,
			passes = 2,
		},
		shadow = {
			enabled = false,
		}

	},
	-- https://wiki.hyprland.org/Configuring/Variables/#animations
	animations = {
		enabled = false,
	},

	-- dwindle {
		--     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		--     preserve_split = true # You probably want this
		-- }


		misc = {
			force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
			disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
			},

			input = {
				kb_layout = "pl",
				--[[ 
				kb_variant =
				kb_model =
				kb_options =
				kb_rules =
				--]]

				follow_mouse = 1,

				sensitivity = 0, -- -1.0 - 1.0

				touchpad = {
					natural_scroll = false
				}
			},

			-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
			device = {
			},

			debug = {
				disable_logs=false
			},
			ecosystem = {
				no_update_news=true
			},
			group = {
				col = {
					border_active = { colors = { active_gradient_start, active_gradient_end }},
				},
				groupbar = {
					col = {
						active = { colors = { active_gradient_start, active_gradient_end }},
						inactive = { colors = { inactive_gradient_start, inactive_gradient_end }},
					},
					font_size = 0,
					height = 0,
				},
			}
		})


--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
	match = {
		class = ".*" ,
	},
	suppress_event = "maximize"
})

-- Fix some dragging issues with XWayland
hl.window_rule({
	match = {
		class = "^$",
		title = "^$",
		xwayland = "1",
		float = "1",
		fullscreen = "0",
		pin = "0",
	},
no_focus = true
})

-- Fix popups getting unnecessarily dimed
hl.window_rule({
	match = { 
		class = "Godot|steam",
		title ="^$",
	},
	no_dim = true
})


