#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='\e[1;36m[\u@\h \w]\$ \e[m'
export EDITOR=nvim
set -o vi
clear
fastfetch
